### ISSUE TITLE
Bootstrap kops cluster

### ISSUE THREAD

**Issue by MeNsaaH** [Go-phie/terraform-aws#5]
https://kops.sigs.k8s.io/terraform/

Cluster should be bootstrapped using terraform

https://github.com/Go-phie/infras-setup/pull/3

The cluster must:
- use dns for api connection 
```diff
+  dns: {}
-   loadBalancer:
-      class: Network
-      type: Public
```

- Enable AWS Authentication: https://kops.sigs.k8s.io/authentication/
- Deploy to the existing VPC
- Enable Necessary Addons
1.  [cert-manager](https://kops.sigs.k8s.io/addons/#cert-manager) and 
2. [aws-load-balancer-controller](https://kops.sigs.k8s.io/addons/#aws-load-balancer-controller)
3. [nodeTerminationHandler](https://kops.sigs.k8s.io/addons/#node-termination-handler) 
4. [Node ProblemDetector](https://kops.sigs.k8s.io/addons/#node-problem-detector)
5. [Pod Identity Webhook](https://kops.sigs.k8s.io/addons/#pod-identity-webhook)

```
# Addons: https://kops.sigs.k8s.io/addons/
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  nodeTerminationHandler:
    enabled: true
    enableRebalanceMonitoring: true
    enableSQSTerminationDraining: true
    managedASGTag: "aws-node-termination-handler/managed"
  nodeProblemDetector:
    enabled: true
    memoryRequest: 32Mi
    cpuRequest: 10m
  podIdentityWebhook:
    enabled: true

```

See https://github.com/bisohns/infras-setup/pull/3
